development:
  dialect: postgres
  database: buff_demo_development
  user: indrajit
  password:
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://indrajit@127.0.0.1:5432/buff_demo_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://indrajit@127.0.0.1:5432/buff_demo_production?sslmode=disable"}}
