name = "buff-demo"
bin = "bin/buff-demo"
vcs = "git"
with_pop = true
with_sqlite = false
with_dep = true
with_webpack = false
with_nodejs = false
with_yarn = false
with_docker = true
with_grifts = true
as_web = false
as_api = true
